services:
  redis:
    image: redis:latest
    container_name: movie-ticket-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - movie-ticket-network

  postgres:
    image: postgres:latest
    container_name: movie-ticket-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - movie-ticket-network

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local

networks:
  movie-ticket-network:
    driver: bridge
