services:
  redis:
    image: redis:latest
    container_name: movie-ticket-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - movie-ticket-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: movie-ticket-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - movie-ticket-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: movie-ticket-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - movie-ticket-network

  postgres:
    image: postgres:latest
    container_name: movie-ticket-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - movie-ticket-network

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local

networks:
  movie-ticket-network:
    driver: bridge
